image: rocker/verse

pages:
  stage: deploy
  script:
      - Rscript -e 'install.packages(c("bookdown"))'
      - Rscript -e "bookdown::render_book('index.Rmd', 'all', output_dir = 'public')"
  artifacts:
    paths:
        - public
  only:
      - master
