image: rocker/tidyverse


before_script:
  - R -e "install.packages('bookdown',repos='http://cran.rstudio.com')"

pages:
  script:
    - R -e "bookdown::render_book('index.Rmd')"
  artifacts:
    paths:
      - public
  only:
    - master
